[TYPER.MACRO]
help = 'Módulo que agrupa macros.'
max_loops_help = 'Número máximo de loops. (default: ∞)'
enable_log_help = 'Habilita o log. (default: false)'
language_help = 'Define a linguagem de execução. (default: pt-br)'
input_mode_help = 'Define o tipo de input. [desktop | gamepad] (default: desktop)'

[TYPER.MATCH]
help = 'Executa o macro responsável por partidas.'
macro_file_help = 'Define arquivo de macro a ser executado.'
