[TYPER.MACRO]
help = 'Module that groups macros.'
max_loops_help = 'Maximum number of loops. (default: ∞)'
enable_log_file_help = 'Enables logging in file. (default: false)'
language_help = 'Sets the execution language.'
input_mode_help = 'Defines the input type. [desktop | gamepad] (default: desktop)'

[TYPER.MATCH]
help = 'Runs the macro responsible for matches.'
difficulty_help = 'Defines the difficulty level to be selected. (default: HERO)'
