name: Release

on:
    workflow_dispatch:
        inputs:
            app_version:
                description: "Application version"
                required: true
                default: "6.0.0"
    push:
        tags:
            - "v*"

permissions:
    contents: write

jobs:
    release:
        strategy:
            fail-fast: false
        matrix:
            python-version: ["3.10"]
            poetry-version: ["latest", "main", "1.8.4"]
            os: [windows-latest]
            runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            
            - name: Install Poetry
              uses: abatilo/actions-poetry@v3
              with:
                poetry-version: ${{ matrix.poetry-version }}
            
            - name: Install dependencies
              run: poetry install --no-interaction

            - name: Build executable
              run: ./scripts/build.ps1

            - name: Determine version
              id: version
              shell: bash
              run: |
                poetry run tufup targets add \
                "${{ steps.version.outputs.VERSION }}" \
                output/ie-vr-macro \
                repo/keys

            - name: Create TUFUP bundle
              run: |
                poetry run tufup targets add "${{ steps.version.outputs.VERSION }}" output/ie-vr-macro repo/keys

            - name: Publish Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      repository/targets/*
