name: Release

on:
    workflow_dispatch:
        inputs:
            app_version:
                description: "Application version"
                required: true
                default: "6.0.0"
    push:
        tags:
            - "v*"

permissions:
    contents: write

jobs:
    release:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Get version
              shell: pwsh
              id: version
              run: |
                if ("${{ github.event_name }}" -eq "push") {
                # Triggered by tag push
                $version = "${{ github.ref_name }}" -replace '^v', ''
                } else {
                # Triggered by workflow_dispatch
                $version = "${{ inputs.app_version }}"
                }
                echo "VERSION=$version" >> $env:GITHUB_OUTPUT
                echo "Version: $version"
            
            - name: Restore keys
              shell: pwsh
              run: |
                [IO.File]::WriteAllBytes(
                    "keys.zip",
                    [Convert]::FromBase64String("${{ secrets.TUF_KEYS_ARCHIVE }}")
                )

                Expand-Archive keys.zip -DestinationPath repo/keys

            - name: Debug extracted keys
              shell: pwsh
              run: |
                dir
                dir keys
            
            - name: Install Poetry
              uses: abatilo/actions-poetry@v3
              with:
                poetry-version: "2.1.3"
            
            - name: Install dependencies
              run: poetry install --without gamepad --no-root --no-interaction -vvv

            - name: Build executable
              run: ./scripts/build.ps1

            - name: Create TUFUP bundle
              run: |
                poetry run tufup targets add ${{ steps.version.outputs.VERSION }} dist/ie-vr-macro repo/keys

            - name: Publish Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      repo/targets/*
                      repo/metadata/*
